NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

**Difference b/w array & list**

*   **Array:**
      Arrays in python can only contain values corresponding to same data type
*   **Lists:**
      Lists in python can contain values corresponding to different data types



In [188]:
#First import numpy library
import numpy as np

In [189]:
num=[1,2,3,4,5]
arr=np.array(num)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [190]:
#Multidimensional Array
num1=[1,2,3,4,5]
num2=[2,4,6,8,10]
num3=[1,3,5,7,9]
Marr=np.array([num1,num2,num3])
print(Marr)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [191]:
#check the shape of the array
Marr.shape

(3, 5)

Most of the Exploratory Data Analysis will be working in 2-dimensional array. Where suppoing will be having a lot of features and lot of rules that can be easily converted. Finally into an array and then apply to a machine. THe reason of using array is that arrays operations are very very fast. So, whenever convert whole dataset into an array after doing all the feature engineering, feature selection and any process what actually will happen that take the data  and apply machine learning algorithm such that training usually takes up quickly because of that extensively using arrays.

In [192]:
Marr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  6,  8],
       [10,  1,  3],
       [ 5,  7,  9]])

In [193]:
Marr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  1,  3,  5,  7,  9]])

**Indexing**

In [194]:
#Accessing the array elements
Marr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [195]:
Marr[2]

array([1, 3, 5, 7, 9])

In [196]:
#slicing
Marr[1:,3:]      #######[rows,columns]

array([[ 8, 10],
       [ 7,  9]])

In [197]:
Marr[1:,2:4]

array([[6, 8],
       [5, 7]])

In [198]:
Marr[1:2,1:4]

array([[4, 6, 8]])

In [199]:
arr

array([1, 2, 3, 4, 5])

In [212]:
#Copy function and broadcasting
arr[2:]=100
arr

array([  1,   2, 100, 100, 100])

Array is actually the reference type.

**Reference Type**
In case of reference type actually sharing the same memory. What'll happen is that any operation do it one variable, that also has the impact the meamory of the other variable. So, in order to prevent that use the function copy.

**Value Type**
A value type can be an integer type i.e. list of integers 

In [218]:
aarr1=arr.copy()
print(aarr1)
aarr1[3:]=300
print(aarr1)

[  1   2 100 100 100]
[  1   2 100 300 300]


In [222]:
#Apply some conditions in Data Exploratory
val=2
print(arr>1)
arr[arr<2]

[False  True  True  True  True]


array([1])

In [203]:
np.arange(0,10).reshape(5,2) #arrange used to quickly create some arrays

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [204]:
np.linspace(1,10,50)    

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In Deep Learning, we need to select some of the points quickly & needs to initialize some points quickly. So, that it can be really helpful. At that time, basically can use arrays

In [205]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)
arr1
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [206]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [225]:
np.ones(4)

array([1., 1., 1., 1.])

In [228]:
np.ones((5,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [229]:
#random distribution
np.random.rand(2,3)

array([[0.40345458, 0.38134574, 0.60636832],
       [0.70257658, 0.33656404, 0.47214303]])

In [209]:
arr_Ran=np.random.rand(4,5)
arr_Ran

array([[0.026332  , 0.76445984, 0.98087066, 0.61531022, 0.13564562],
       [0.93675233, 0.77433827, 0.1669579 , 0.67293098, 0.60916433],
       [0.9599026 , 0.98775458, 0.23565518, 0.11238139, 0.5965065 ],
       [0.63597724, 0.32051767, 0.87118216, 0.22477268, 0.3507338 ]])

In [230]:
np.random.randint(0,100,8).reshape(4,2)

array([[ 7, 72],
       [85, 38],
       [71, 61],
       [92,  9]])

In [211]:
np.random.random_sample((1,5))

array([[0.88625058, 0.77559263, 0.05518117, 0.68713449, 0.74716033]])